{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2023-09-19T21:44:51.639572100Z",
     "start_time": "2023-09-19T21:44:38.559584600Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/bin/bash: /home/yurid/miniconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)\r\n",
      "Requirement already satisfied: pandas in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (2.1.0)\r\n",
      "Requirement already satisfied: numpy>=1.22.4 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from pandas) (1.24.3)\r\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from pandas) (2.8.2)\r\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from pandas) (2023.3.post1)\r\n",
      "Requirement already satisfied: tzdata>=2022.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from pandas) (2023.3)\r\n",
      "Requirement already satisfied: six>=1.5 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\r\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "/bin/bash: /home/yurid/miniconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)\r\n",
      "Requirement already satisfied: pydmd in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (0.4.1.post2308)\r\n",
      "Requirement already satisfied: numpy in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from pydmd) (1.24.3)\r\n",
      "Requirement already satisfied: scipy in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from pydmd) (1.11.2)\r\n",
      "Requirement already satisfied: matplotlib in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from pydmd) (3.8.0)\r\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib->pydmd) (1.1.1)\r\n",
      "Requirement already satisfied: cycler>=0.10 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib->pydmd) (0.11.0)\r\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib->pydmd) (4.42.1)\r\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib->pydmd) (1.4.5)\r\n",
      "Requirement already satisfied: packaging>=20.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib->pydmd) (23.1)\r\n",
      "Requirement already satisfied: pillow>=6.2.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib->pydmd) (10.0.1)\r\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib->pydmd) (3.1.1)\r\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib->pydmd) (2.8.2)\r\n",
      "Requirement already satisfied: importlib-resources>=3.2.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib->pydmd) (6.0.1)\r\n",
      "Requirement already satisfied: zipp>=3.1.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib->pydmd) (3.16.2)\r\n",
      "Requirement already satisfied: six>=1.5 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->pydmd) (1.16.0)\r\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "/bin/bash: /home/yurid/miniconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)\r\n",
      "Requirement already satisfied: scikit-learn in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (1.3.0)\r\n",
      "Requirement already satisfied: numpy>=1.17.3 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from scikit-learn) (1.24.3)\r\n",
      "Requirement already satisfied: scipy>=1.5.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from scikit-learn) (1.11.2)\r\n",
      "Requirement already satisfied: joblib>=1.1.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from scikit-learn) (1.3.2)\r\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from scikit-learn) (3.2.0)\r\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "/bin/bash: /home/yurid/miniconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)\r\n",
      "Requirement already satisfied: matplotlib in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (3.8.0)\r\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib) (1.1.1)\r\n",
      "Requirement already satisfied: cycler>=0.10 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib) (0.11.0)\r\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib) (4.42.1)\r\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib) (1.4.5)\r\n",
      "Requirement already satisfied: numpy<2,>=1.21 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib) (1.24.3)\r\n",
      "Requirement already satisfied: packaging>=20.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib) (23.1)\r\n",
      "Requirement already satisfied: pillow>=6.2.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib) (10.0.1)\r\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib) (3.1.1)\r\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib) (2.8.2)\r\n",
      "Requirement already satisfied: importlib-resources>=3.2.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib) (6.0.1)\r\n",
      "Requirement already satisfied: zipp>=3.1.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.16.2)\r\n",
      "Requirement already satisfied: six>=1.5 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)\r\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "/bin/bash: /home/yurid/miniconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)\r\n",
      "Requirement already satisfied: seaborn in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (0.12.2)\r\n",
      "Requirement already satisfied: numpy!=1.24.0,>=1.17 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from seaborn) (1.24.3)\r\n",
      "Requirement already satisfied: pandas>=0.25 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from seaborn) (2.1.0)\r\n",
      "Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from seaborn) (3.8.0)\r\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.1.1)\r\n",
      "Requirement already satisfied: cycler>=0.10 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.11.0)\r\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.42.1)\r\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.5)\r\n",
      "Requirement already satisfied: packaging>=20.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (23.1)\r\n",
      "Requirement already satisfied: pillow>=6.2.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (10.0.1)\r\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.1.1)\r\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)\r\n",
      "Requirement already satisfied: importlib-resources>=3.2.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (6.0.1)\r\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from pandas>=0.25->seaborn) (2023.3.post1)\r\n",
      "Requirement already satisfied: tzdata>=2022.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from pandas>=0.25->seaborn) (2023.3)\r\n",
      "Requirement already satisfied: zipp>=3.1.0 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib!=3.6.1,>=3.1->seaborn) (3.16.2)\r\n",
      "Requirement already satisfied: six>=1.5 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)\r\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "/bin/bash: /home/yurid/miniconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)\r\n",
      "Requirement already satisfied: keras_tuner in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (1.3.5)\r\n",
      "Requirement already satisfied: packaging in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from keras_tuner) (23.1)\r\n",
      "Requirement already satisfied: requests in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from keras_tuner) (2.31.0)\r\n",
      "Requirement already satisfied: kt-legacy in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from keras_tuner) (1.0.5)\r\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from requests->keras_tuner) (3.2.0)\r\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from requests->keras_tuner) (3.4)\r\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from requests->keras_tuner) (1.26.16)\r\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (from requests->keras_tuner) (2023.7.22)\r\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "/bin/bash: /home/yurid/miniconda3/envs/tf/lib/libtinfo.so.6: no version information available (required by /bin/bash)\r\n",
      "Requirement already satisfied: keras in /home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages (2.13.1)\r\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install pandas\n",
    "%pip install pydmd\n",
    "%pip install scikit-learn\n",
    "%pip install matplotlib\n",
    "%pip install seaborn\n",
    "%pip install keras_tuner\n",
    "%pip install keras\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true,
    "ExecuteTime": {
     "end_time": "2023-09-23T15:01:59.964344Z",
     "start_time": "2023-09-23T15:01:59.800243200Z"
    }
   },
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'src'",
     "output_type": "error",
     "traceback": [
      "\u001B[0;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[0;31mModuleNotFoundError\u001B[0m                       Traceback (most recent call last)",
      "Cell \u001B[0;32mIn[1], line 3\u001B[0m\n\u001B[1;32m      1\u001B[0m \u001B[38;5;28;01mimport\u001B[39;00m \u001B[38;5;21;01mgc\u001B[39;00m\n\u001B[0;32m----> 3\u001B[0m \u001B[38;5;28;01mfrom\u001B[39;00m \u001B[38;5;21;01msrc\u001B[39;00m\u001B[38;5;21;01m.\u001B[39;00m\u001B[38;5;21;01mfiller\u001B[39;00m \u001B[38;5;28;01mimport\u001B[39;00m dmd_filler, interpolate_filler, fill_df\n\u001B[1;32m      4\u001B[0m \u001B[38;5;28;01mfrom\u001B[39;00m \u001B[38;5;21;01msrc\u001B[39;00m\u001B[38;5;21;01m.\u001B[39;00m\u001B[38;5;21;01mdataframe\u001B[39;00m \u001B[38;5;28;01mimport\u001B[39;00m read_data, windowing, split_data, show_error_metrics\n\u001B[1;32m      5\u001B[0m \u001B[38;5;28;01mfrom\u001B[39;00m \u001B[38;5;21;01msrc\u001B[39;00m\u001B[38;5;21;01m.\u001B[39;00m\u001B[38;5;21;01mscaler\u001B[39;00m \u001B[38;5;28;01mimport\u001B[39;00m Scaler\n",
      "\u001B[0;31mModuleNotFoundError\u001B[0m: No module named 'src'"
     ]
    }
   ],
   "source": [
    "import gc\n",
    "\n",
    "from src.filler import dmd_filler, interpolate_filler, fill_df\n",
    "from src.dataframe import read_data, windowing, split_data, show_error_metrics\n",
    "from src.scaler import Scaler\n",
    "from src.model import train_model, hp_search\n",
    "from src.model import hp_search, build_model\n",
    "from keras.callbacks import EarlyStopping\n",
    "from matplotlib import pyplot\n",
    "import pandas as pd\n",
    "from keras.models import Sequential\n",
    "from keras.layers import LSTM\n",
    "from keras.layers import Bidirectional, Dropout, Activation, Dense, LSTM, InputLayer\n",
    "from keras.callbacks import EarlyStopping\n",
    "import keras\n",
    "\n",
    "import numpy as np\n",
    "from pydmd import DMD"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2023-09-19T21:44:51.862281300Z",
     "start_time": "2023-09-19T21:44:51.812985300Z"
    }
   },
   "outputs": [],
   "source": [
    "cities = {\n",
    "    'barbacena': 'daily_barbacena',\n",
    "    'juiz de fora': 'daily_juiz de fora',\n",
    "    'muriae': 'daily_muriae',\n",
    "    'sao joao del rei': 'daily_sao joao del rei',\n",
    "    'vicosa': 'daily_vicosa'\n",
    "}\n",
    "\n",
    "fillers = {'dmd':dmd_filler, 'interpolate':interpolate_filler}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Trial 21 Complete [00h 08m 44s]\n",
      "val_loss: 0.021206262148916723\n",
      "\n",
      "Best val_loss So Far: 0.021160120144486427\n",
      "Total elapsed time: 00h 08m 44s\n",
      "\n",
      "Search: Running Trial #22\n",
      "\n",
      "Value             |Best Value So Far |Hyperparameter\n",
      "384               |288               |units\n",
      "0.1               |0.25              |dropout\n",
      "160               |416               |units_2\n",
      "relu              |sigmoid           |activation\n",
      "0.01              |0.01              |learning_rate\n",
      "Epoch 1/15\n",
      "145/145 [==============================] - 7s 31ms/step - loss: 0.2714 - val_loss: 0.2942\n",
      "Epoch 2/15\n",
      "145/145 [==============================] - 4s 25ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 3/15\n",
      "145/145 [==============================] - 4s 24ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 4/15\n",
      "145/145 [==============================] - 4s 24ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 5/15\n",
      "145/145 [==============================] - 4s 28ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 6/15\n",
      "145/145 [==============================] - 4s 26ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 7/15\n",
      "145/145 [==============================] - 4s 27ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 8/15\n",
      "145/145 [==============================] - 4s 26ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 9/15\n",
      "145/145 [==============================] - 4s 27ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 10/15\n",
      "145/145 [==============================] - 5s 35ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 11/15\n",
      "145/145 [==============================] - 5s 33ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 12/15\n",
      "145/145 [==============================] - 4s 30ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 13/15\n",
      "145/145 [==============================] - 5s 32ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 14/15\n",
      "145/145 [==============================] - 5s 32ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 15/15\n",
      "145/145 [==============================] - 4s 27ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 1/15\n",
      "145/145 [==============================] - 8s 34ms/step - loss: 0.3525 - val_loss: 0.2942\n",
      "Epoch 2/15\n",
      "145/145 [==============================] - 4s 30ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 3/15\n",
      "145/145 [==============================] - 4s 30ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 4/15\n",
      "145/145 [==============================] - 4s 28ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 5/15\n",
      "145/145 [==============================] - 5s 36ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 6/15\n",
      "145/145 [==============================] - 4s 27ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 7/15\n",
      "145/145 [==============================] - 4s 28ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 8/15\n",
      "145/145 [==============================] - 4s 29ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 9/15\n",
      "145/145 [==============================] - 4s 29ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 10/15\n",
      "145/145 [==============================] - 4s 29ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 11/15\n",
      "145/145 [==============================] - 4s 29ms/step - loss: 0.2697 - val_loss: 0.2942\n",
      "Epoch 12/15\n",
      "127/145 [=========================>....] - ETA: 0s - loss: 0.2713Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_50079/3729540775.py\", line 20, in <module>\n",
      "    hp = hp_search(name,\n",
      "  File \"/home/yurid/git/tcc/notebook/src/model.py\", line 62, in hp_search\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py\", line 230, in search\n",
      "    self._try_run_and_update_trial(trial, *fit_args, **fit_kwargs)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py\", line 270, in _try_run_and_update_trial\n",
      "    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py\", line 235, in _run_and_update_trial\n",
      "    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/keras_tuner/engine/tuner.py\", line 287, in run_trial\n",
      "    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/keras_tuner/engine/tuner.py\", line 214, in _build_and_fit_model\n",
      "    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/keras_tuner/engine/hypermodel.py\", line 144, in fit\n",
      "    return model.fit(*args, **kwargs)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/keras/src/engine/training.py\", line 1742, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py\", line 150, in error_handler\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 825, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py\", line 857, in _call\n",
      "    return self._no_variable_creation_fn(*args, **kwds)  # pylint: disable=not-callable\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py\", line 148, in __call__\n",
      "    return concrete_function._call_flat(\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py\", line 1349, in _call_flat\n",
      "    return self._build_call_outputs(self._inference_function(*args))\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py\", line 196, in __call__\n",
      "    outputs = self._bound_context.call_function(\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/eager/context.py\", line 1457, in call_function\n",
      "    outputs = execute.execute(\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 53, in quick_execute\n",
      "    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2120, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1326, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1173, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 1088, in format_exception_as_a_whole\n",
      "    frames.append(self.format_record(record))\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 970, in format_record\n",
      "    frame_info.lines, Colors, self.has_colors, lvals\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/IPython/core/ultratb.py\", line 792, in lines\n",
      "    return self._sd.lines\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/stack_data/utils.py\", line 144, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/stack_data/core.py\", line 734, in lines\n",
      "    pieces = self.included_pieces\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/stack_data/utils.py\", line 144, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/stack_data/core.py\", line 681, in included_pieces\n",
      "    pos = scope_pieces.index(self.executing_piece)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/stack_data/utils.py\", line 144, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/stack_data/core.py\", line 660, in executing_piece\n",
      "    return only(\n",
      "  File \"/home/yurid/miniconda3/envs/tf/lib/python3.9/site-packages/executing/executing.py\", line 190, in only\n",
      "    raise NotOneValueFound('Expected one value, found 0')\n",
      "executing.executing.NotOneValueFound: Expected one value, found 0\n"
     ]
    }
   ],
   "source": [
    "for city in cities:\n",
    "    for filler in fillers:\n",
    "        print(f'=== {city} = {filler} ===')\n",
    "\n",
    "        name = f'{filler}_lstm_5_1_{city}'\n",
    "\n",
    "        # read\n",
    "        file = f'../data/{cities[city]}.csv'\n",
    "        df = read_data(file)\n",
    "        df = fill_df(df, fillers[filler])\n",
    "\n",
    "        # scaler\n",
    "        scaler = Scaler(df)\n",
    "        df_scaled = scaler.get_dataframe_scaled()\n",
    "\n",
    "        # windowing\n",
    "        X, Y = windowing(df_scaled, 5, 1)\n",
    "        train_x, train_y, test_x, test_y = split_data(X, Y, length=len(df_scaled), ratio=0.9)\n",
    "\n",
    "        hp = hp_search(name,\n",
    "                       train_x,\n",
    "                       train_y,\n",
    "                       max_trials=50,\n",
    "                       executions_per_trial=10,\n",
    "                       epochs=15,\n",
    "                       validation_split=0.3,\n",
    "                       verbose=1)\n",
    "\n",
    "        model = build_model(hp)\n",
    "        print(hp.values)\n",
    "\n",
    "\n",
    "        # fit network\n",
    "        model = train_model(model,\n",
    "                            train_x=train_x,\n",
    "                            train_y=train_y,\n",
    "                            name_model=f'model_{name}',\n",
    "                            batch_size=72,\n",
    "                            verbose=1,\n",
    "                            early_stopping_patience= 100,\n",
    "                            cache_path='./cache')\n",
    "\n",
    "\n",
    "        scores = model.evaluate(X, Y, verbose=0)\n",
    "        print(scores)\n",
    "\n",
    "\n",
    "        # predict\n",
    "        predict = model.predict(test_x)\n",
    "        real = scaler.scales['RADIATION'].inverse_transform(test_y.reshape(-1,1))\n",
    "        predict = scaler.scales['RADIATION'].inverse_transform(predict)\n",
    "\n",
    "        # show predict\n",
    "        range_plot = 100\n",
    "        pyplot.plot(real[0:range_plot], color='blue', label='real')\n",
    "        pyplot.plot(predict[0:range_plot], color='red', label='incompleto')\n",
    "        pyplot.show()\n",
    "\n",
    "        show_error_metrics(real, predict)\n",
    "\n",
    "        print('\\n\\n\\n')\n",
    "        gc.collect()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "start_time": "2023-09-19T21:55:45.376572200Z"
    }
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "tf",
   "language": "python",
   "name": "tf"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
